# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  use_frameworks!
  platform :ios, '14.0'
  pod 'Mach1SpatialAPI', :path => 'Pod-Mach1SpatialAPI'
end
